### ISSUE TITLE
Original publication of the script

### ISSUE THREAD

**Issue by Theresa-S** [jo-mueller/FociCounter#15]
... is in my opinion this one: https://www.mdpi.com/2072-6694/12/6/1589

Suckert, T.; Rassamegevanon, T.; Müller, J.; Dietrich, A.; Graja, A.; Reiche, M.; Löck, S.; Krause, M.; Beyreuther, E.; von Neubeck, C. Applying Tissue Slice Culture in Cancer Research—Insights from Preclinical Proton Radiotherapy. Cancers 2020, 12, 1589. https://doi.org/10.3390/cancers12061589 

--> still without the StarDist for nuclei segmentation, but the main concept is already described here. Plus, we validated it ;-)

**Comment by jo-mueller** [comment]
Hm...then I think it would make sense to add both papers to the papers to cite. The one you pointed out (which is the one I was looking for, I think, but I lost track^^") - and the one from Annina, for which I implemented StarDist and a bunch of other notable features.
