### ISSUE TITLE
spheroid distance map

### ISSUE THREAD

**Issue by Franzi-ba** [jo-mueller/FociCounter#16]
It would be nice to include a distance map so the distance is measured for each individual focus from the outer rim of the spheroid in microns. 
Thanks in advance!

**Comment by jo-mueller** [comment]
Hi @Franzi-ba ,

there's a new script version for this [here](https://github.com/jo-mueller/FociCounter/blob/introduce-spheroid-version/FociCounter_basic_spheroid.ijm). Can you check if the results make sense to you? You'll see that the `measurements_avg` now contains a new column `distance_to_edge`, the nucleus segmentation/spheroid segmentation and the distance map are now also among the exported  data.

**Comment by annelinaw** [comment]
Hi @jo-mueller ,
it would be nice to include the gaussain blur and correct the measurement of the distance map (see email). Also I wonder if it would be possible the get the distance from outer rim for each individuell cell, not just for the positive ones. That would be really helpful. Thanks in advance!

**Comment by jo-mueller** [comment]
Hi @annelinaw @Franzi-ba ,

I merged the updated code into the main repository and created a new release (right hand side). Whenever you use the code somewhere down the road, it would be good practice to cite the link to the repository as well as the used version of the script, e.g. 0.2.0
